### ISSUE TITLE
Goals, plan, ideas?

### ISSUE THREAD

**Issue by dumblob** [RealNeGate/Cuik#1]
Just curious - what are the goals, plans, and ideas behind this cool-looking repo?

**Comment by RealNeGate** [comment]
Ideally somewhere around 0.5-1.5 Million line compiles, mostly being compatible with Clang/GCC and MSVC with a few of there extensions and some new ones of my own.

**Comment by dumblob** [comment]
Ok, so full C21 compatibility + zero optimizations and quick interpretation (or maybe compilation once the IR gets lowered by your home-grown ASM emitter)?

**Comment by RealNeGate** [comment]
There will be an optimizer but the debug builds will be fast, C11 support at minimum i'll maybe take some new features as things go along and it's not an ASM emitter it's a custom backend I've been writing which outputs object files and machine code no assembly.

**Comment by dumblob** [comment]
Ok, thanks for clarification! Closing for lack of further actionable items.
