### ISSUE TITLE
Basic function declaration and compilation issues

### ISSUE THREAD

**Issue by Goubermouche** [RealNeGate/Cuik#26]
I'm trying to create a simple function which returns a number in TB, but I'm having trouble doing so. This is my attempt: 

```c
#include "tb/include/tb.h"
#define CUIK_USE_TB

int main() {
    TB_FeatureSet features = { 0 };
    TB_Module* module = tb_module_create_for_host(&features, false);
    TB_Function* function = tb_function_create(module, 4, "add", TB_LINKAGE_PRIVATE, TB_COMDAT_NONE);
    TB_Node* number = tb_inst_sint(function, TB_TYPE_I64, 200);

    tb_inst_ret(function, 0, NULL);

    TB_Passes* p = tb_pass_enter(function, tb_function_get_arena(function));
    tb_pass_codegen(p, true);
    return 0;
}
```
When I run the above code I'd expect it to compile the function and print the respective assembly (the print_asm flag is set to true), but I crash as soon as I get to the `tb_inst_sint` call. I'm most definitely doing something obvious incorrectly, but I'm not sure what, since when I went to check out the documentation the builder section was blank, which is perfectly understandable, thanks to the stage of the project. Any help related to getting this running is greatly appreciated!

**Comment by RealNeGate** [comment]
Yes, the code is missing a `TB_FunctionPrototype*`, you can use `tb_function_set_prototype` to do that. also the `emit_asm` flag on `tb_pass_codegen` does not print assembly, it just emits it into a buffer you can then do: ```c
TB_FunctionOutput* out = tb_pass_codegen(p, true);
tb_output_print_asm(out, stdout);
```
to put it into standard out, you can also do `tb_output_get_asm` to extract it from the buffer, note that the assembly output is split into large chunks so if you need it sequential you'll have to do that manually.

**Comment by Goubermouche** [comment]
Perfect, this works as expected, thanks a bunch.
