### ISSUE TITLE
Support for smaller addressing modes of registers

### ISSUE THREAD

**Issue by Goubermouche** [RealNeGate/Cuik#28]
Hi, I was wondering if you're ever planning to add support for different addressing modes for registers (RAX - EAX ...), and if so, how high/low it is on your to-do list.

**Comment by RealNeGate** [comment]
Sorry, what's this in reference to? codegen or disassembler? because in terms of codegen currently all except the high regs are accessible (no AH, CH, DH, BH)

**Comment by Goubermouche** [comment]
Ah, my bad 😄, I was talking about the code generator, but I must've missed that you're doing it. I was trying to do something like this: 

```rust
i32 test() {
    i32 a = 100;
    i32 b = 200;

    return a + b;
}
```

And the generated assembly was using the entire RAX and RCX (iirc) registers, which got me a bit confused as it was using the entirety of the 64 bit registers to store 32 bit values, but on second thought I guess it doesn't really matter in this case.

**Comment by RealNeGate** [comment]
Yea, the old assembler didn't display register labels differently for size, that's now fixed since it's doing a proper disassembler job and not just lazily logging what i do
