### ISSUE TITLE
This reply I take issue with.

### ISSUE THREAD

**Issue by creikey** [RealNeGate/Cuik#31]
Wack ass unformatted github issue... Yea i just haven't gotten around to seriously testing or working with mac, help wanted

_Originally posted by @RealNeGate in https://github.com/RealNeGate/Cuik/issues/29#issuecomment-1793375063_

**Comment by RealNeGate** [comment]
![image](https://github.com/RealNeGate/Cuik/assets/12993638/92405045-7a36-4568-866e-a2da3efee6d9)

**Comment by creikey** [comment]
H9ow do I reopen an issue

**Comment by RealNeGate** [comment]
Filtered

**Comment by creikey** [comment]
/
/
/
/
/
/
/
/ GRRRRRRR GRRRRRRRRRRRRR *ANGRY*
