### ISSUE TITLE
This SHOULDN'T HAve bee nclosed

### ISSUE THREAD

**Issue by creikey** [RealNeGate/Cuik#32]
![image](https://github.com/RealNeGate/Cuik/assets/12993638/92405045-7a36-4568-866e-a2da3efee6d9)

_Originally posted by @RealNeGate in https://github.com/RealNeGate/Cuik/issues/31#issuecomment-1822270105_

**Comment by RealNeGate** [comment]
![1662726633315932](https://github.com/RealNeGate/Cuik/assets/12993638/a6b4f800-566c-49ed-b0e7-e3723fc0b256)
