### ISSUE TITLE
Bad Vibes from identity_int_binop

### ISSUE THREAD

**Issue by ShawSumma** [RealNeGate/Cuik#35]
Something is wrong in the optimizer.

`identify_int_binop` has bad vibes.

It claims `a * b = b` when b is zero... but it is coded like `a * b = a` when b is zero.

should this:
```
        case TB_SHL:
        case TB_SHR:
        case TB_ADD:
        case TB_SUB:
        case TB_MUL:
        case TB_XOR:
        return n->inputs[1];
```

be:
```
        case TB_SHL:
        case TB_SHR:
        case TB_ADD:
        case TB_SUB:
        case TB_XOR:
        return n->inputs[1];
        case TB_MUL:
        return n->inputs[2];
```

Or am i loosing my mind.

**Comment by RealNeGate** [comment]
Fixed: https://github.com/RealNeGate/Cuik/commit/5886e006b30afa5491139be0017d2ff121bfc80d
![image](https://github.com/RealNeGate/Cuik/assets/12993638/4ec2934b-b27c-4f3c-b286-6269d3bbb5db)
