### ISSUE TITLE
New Codegen (new-cg) does't align stack depending on TB_FEATURE_FRAME_PTR

### ISSUE THREAD

**Issue by ShawSumma** [RealNeGate/Cuik#40]
When `TB_FEATURE_FRAME_PTR` is a feature changes alignment of stack, it just pushes without changing stack space used.

```asm
main:
  push rbp
  mov rbp, rsp
  sub rsp, 88
```
vs
```asm
main:
  sub rsp, 88
```
one of these is wrong. It would be good to get right.

**Comment by ShawSumma** [comment]
Checked this only on Linux BTW, might be different on windows.

**Comment by RealNeGate** [comment]
Fixed stack layout bs btw
