### ISSUE TITLE
How to compile successfully on windows

### ISSUE THREAD

**Issue by icyfox168168** [RealNeGate/Cuik#7]
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
20 errors generated.
20 errors generated.
lld-link: error: build\arena.obj: machine type x86 conflicts with x64
lld-link: error: build\atoms.obj: machine type x86 conflicts with x64
lld-link: error: build\big_array.obj: machine type x86 conflicts with x64
lld-link: error: build\crash_handler.obj: machine type x86 conflicts with x64
lld-link: error: build\diagnostic.obj: machine type x86 conflicts with x64
lld-link: error: build\lexer.obj: machine type x86 conflicts with x64
lld-link: error: build\linker.obj: machine type x86 conflicts with x64
lld-link: error: build\microsoft_craziness.obj: machine type x86 conflicts with x64
lld-link: error: build\tblink.obj: machine type x86 conflicts with x64
lld-link: error: build\threads_msvc.obj: machine type x86 conflicts with x64
lld-link: error: build\tls.obj: machine type x86 conflicts with x64
lld-link: error: could not open 'ole32.lib': no such file or directory
lld-link: error: could not open 'Advapi32.lib': no such file or directory
lld-link: error: could not open 'OleAut32.lib': no such file or directory
lld-link: error: could not open 'DbgHelp.lib': no such file or directory
lld-link: error: could not open 'libcmt.lib': no such file or directory

**Comment by bumbread** [comment]
Are you on 32-bit machine?

**Comment by icyfox168168** [comment]
I have been following this project for a long time, but it has not been able to compile successfully in win10 64, the system has vs2022 gcc clang

**Comment by bumbread** [comment]
This error usually happens when you launch 32-bit vcvars before running the build script. Can you try running `set Platform` in the same command line where you launch the build script?
